cookie:
  expiry_days: 30
  key: 3dawda21312
  name: flight_scraper_session
credentials:
  usernames:
    ab@ab.ab:
      email: ab@ab.ab
      first_name: awd
      last_name: dwa
      logged_in: false
      password: $2b$12$8sTlowAZGrz04Dr3xTfACOOaoIzpBFvAhHfncv.BsnsMhjQudGvYW
      password_hint: '123'
      roles: null
    ab@ab.abc:
      email: ab@ab.abc
      first_name: awd
      last_name: dwa
      logged_in: false
      password: $2b$12$337I5Oh4UD2XjxD1E6geR.17IOOnfTLheFIgtV4bf125KuCQa4O2C
      password_hint: '123'
      roles: null
    abc@abc.abc:
      email: abc@abc.abc
      first_name: dwadaw
      last_name: adwawd
      logged_in: false
      password: $2b$12$GxxJn3p68b2RQuWOU9vxMOwztXvO9Jr1ilWpc1Q.OrofWYaSP8PHS
      password_hint: '1231'
      roles: null
    abc@abc.abca:
      email: abc@abc.abca
      first_name: dwadaw
      last_name: adwawd
      logged_in: false
      password: $2b$12$GluVOpIpu7JsevqsvLAr2uG3ATiTiHmn2VX743zF2zgePeHqmGKaO
      password_hint: '1231'
      roles: null
    bakica123@gmail.com:
      email: bakica123@gmail.com
      first_name: Luka
      last_name: bona
      logged_in: false
      password: $2b$12$UXaqAC/yC6UNion9AkLQcuBMjZwir4rDBekgRy5nDIZqrV/REgTV6
      password_hint: '123'
      roles: null
    hpt@hpt.com:
      email: hpt@hpt.com
      first_name: dwa
      last_name: daw
      logged_in: false
      password: $2b$12$Aouyj3K02wXhOnOw7j5qd.BAGnCkNb.0cA4la8z7Bo.NIquUmYQkm
      password_hint: '231'
      roles: null
    izvimubaski@serbian.abca:
      email: IZVIMUBASKI@serbian.abca
      failed_login_attempts: 0
      first_name: J NISAM
      last_name: MALI PARADAJZ
      logged_in: false
      password: $2b$12$t1186w4Wh8iPTmowbAcofeuJo44b6dwBsrS5wdi355A6LdRCMffnC
      password_hint: '1231'
      roles: null
    izvimubaskiabc@abc.abca:
      email: IZVIMUBASKIabc@abc.abca
      first_name: JA SAM
      last_name: MALI PARADAJZ
      logged_in: false
      password: $2b$12$/NHl9FnIiYnwmrf0Mh5ncumekCu2WGc3xp1FnHIt9uOJo5rqT8/E2
      password_hint: '1231'
      roles: null
    jsmith@gmail.com:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$csTcEjfiskv5QmUdPHVaH.wxjsCnncnjuw3VM7s4V.XsK.ubOECRG
    luka.razem@gmail.com:
      email: luka.razem@gmail.com
      first_name: Luka
      last_name: Razem
      logged_in: false
      password: $2b$12$WxtylhfMdnM4uUImvOHxM.YMAspKDCCRianKKnZAazWzJ0EL7fkRW
      password_hint: '213'
      roles: null
    luka.razema@gmail.com:
      email: luka.razema@gmail.com
      first_name: Luka
      last_name: Razem
      logged_in: false
      password: $2b$12$4aYkgNmF3Jc7eNamKHnaB.WMBpxtHEbypm6SqzwfAbV0tY1XFmvAa
      password_hint: '213'
      roles: null
    razemluka@gmail.com:
      email: razemluka@gmail.com
      first_name: Luka
      last_name: Razem
      logged_in: false
      password: $2b$12$R106oQ.7pdixiCdwjRocSOzcdnjSHvPxx4/vZKM4V3z7.Rwf0atWi
      password_hint: '3123'
      roles: null
